# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

csv2dataframe <- function(url, ...) {
    options = list(...)
    options['fileType'] = 'csv'
    ddc_read(url, options)
}

orc2dataframe <- function(url, ...) {
    options = list(...)
    options['fileType'] = 'orc'
    ddc_read(url, options)
}

object2hdfs <- function(object, url, ...) {
    ddc_write(object, url, list(...))
}
