# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hdfs_write <- function(object, url, ...) {
    .Call('hdfsconnector_ddc_write', PACKAGE = 'hdfsconnector', object, url, list(...))
}

hdfs_read <- function(url, ...) {
    .Call('hdfsconnector_ddc_read', PACKAGE = 'hdfsconnector', url, list(...))
}

