# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ddc_write <- function(object, url, options) {
    .Call('hdfsconnector_ddc_write', PACKAGE = 'hdfsconnector', object, url, options)
}

ddc_read <- function(url, options) {
    .Call('hdfsconnector_ddc_read', PACKAGE = 'hdfsconnector', url, options)
}

create_plan <- function(url, options, workerMapR) {
    .Call('hdfsconnector_create_plan', PACKAGE = 'hdfsconnector', url, options, workerMapR)
}

