# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ddc_write <- function(object, url, ...) {
    options = list(...)
    if(!("hdfsConfigurationFile" %in% options)) {
        # set default hdfsConfigurationFile
        options["hdfsConfigurationFile"] = paste(system.file(package='ddc'),'/conf/hdfs.json',sep='')
    }

    if (typeof(object) == 'character') {
        .Call('ddc_ddc_write', PACKAGE = 'ddc', object, url, options)
    }
    else {
        .Call('ddc_ddc_write', PACKAGE = 'ddc', serialize(object, NULL), url, options)
    }

}

ddc_read <- function(url, ...) {
    options = list(...)
    if(!("hdfsConfigurationFile" %in% options)) {
        # set default hdfsConfigurationFile
        options["hdfsConfigurationFile"] = paste(system.file(package='ddc'),'/conf/hdfs.json',sep='')
    }

    .Call('ddc_ddc_read', PACKAGE = 'ddc', url, options)
}

