# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ddc_write <- function(object, url, ...) {
    .Call('ddc_ddc_write', PACKAGE = 'ddc', object, url, list(...))
}

ddc_read <- function(url, ...) {
    .Call('ddc_ddc_read', PACKAGE = 'ddc', url, list(...))
}

