# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ddc_write <- function(object, url, options) {
    .Call('ddc_ddc_write', PACKAGE = 'ddc', object, url, options)
}

ddc_read <- function(url, options) {
    .Call('ddc_ddc_read', PACKAGE = 'ddc', url, options)
}

